"""rename_tables

Revision ID: 70d2bb0c5774
Revises: 9fc817f5a81d
Create Date: 2025-02-02 19:30:22.848594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70d2bb0c5774'
down_revision: Union[str, None] = '9fc817f5a81d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=False)
    op.create_table('officers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id', 'email')
    )
    op.create_index(op.f('ix_officers_email'), 'officers', ['email'], unique=False)
    op.create_index(op.f('ix_officers_first_name'), 'officers', ['first_name'], unique=False)
    op.create_index(op.f('ix_officers_id'), 'officers', ['id'], unique=False)
    op.create_index(op.f('ix_officers_last_name'), 'officers', ['last_name'], unique=False)

    op.drop_index('ix_officer_email', table_name='officer')
    op.drop_index('ix_officer_first_name', table_name='officer')
    op.drop_index('ix_officer_id', table_name='officer')
    op.drop_index('ix_officer_last_name', table_name='officer')
    op.drop_table('officer')
    op.drop_index('ix_department_id', table_name='department')
    op.drop_index('ix_department_name', table_name='department')
    op.drop_table('department')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officer',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name='officer_department_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'email', name='officer_pkey')
    )
    op.create_index('ix_officer_last_name', 'officer', ['last_name'], unique=False)
    op.create_index('ix_officer_id', 'officer', ['id'], unique=False)
    op.create_index('ix_officer_first_name', 'officer', ['first_name'], unique=False)
    op.create_index('ix_officer_email', 'officer', ['email'], unique=False)
    op.create_table('department',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='department_pkey')
    )
    op.create_index('ix_department_name', 'department', ['name'], unique=False)
    op.create_index('ix_department_id', 'department', ['id'], unique=False)
    op.drop_index(op.f('ix_officers_last_name'), table_name='officers')
    op.drop_index(op.f('ix_officers_id'), table_name='officers')
    op.drop_index(op.f('ix_officers_first_name'), table_name='officers')
    op.drop_index(op.f('ix_officers_email'), table_name='officers')
    op.drop_table('officers')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
