"""db_init

Revision ID: 9fc817f5a81d
Revises: 
Create Date: 2025-02-02 19:27:56.300847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc817f5a81d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_id'), 'department', ['id'], unique=False)
    op.create_index(op.f('ix_department_name'), 'department', ['name'], unique=False)
    op.create_table('officer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id', 'email')
    )
    op.create_index(op.f('ix_officer_email'), 'officer', ['email'], unique=False)
    op.create_index(op.f('ix_officer_first_name'), 'officer', ['first_name'], unique=False)
    op.create_index(op.f('ix_officer_id'), 'officer', ['id'], unique=False)
    op.create_index(op.f('ix_officer_last_name'), 'officer', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_officer_last_name'), table_name='officer')
    op.drop_index(op.f('ix_officer_id'), table_name='officer')
    op.drop_index(op.f('ix_officer_first_name'), table_name='officer')
    op.drop_index(op.f('ix_officer_email'), table_name='officer')
    op.drop_table('officer')
    op.drop_index(op.f('ix_department_name'), table_name='department')
    op.drop_index(op.f('ix_department_id'), table_name='department')
    op.drop_table('department')
    # ### end Alembic commands ###
